// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;

namespace Nethermind.Grandine
{
    internal static unsafe partial class NativeMethods
    {
        [DllImport("/home/paul/Desktop/blockchain/grandine_a/grandine/target/release/libc_grandine.so", EntryPoint = "grandine_run", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ulong grandine_run(ulong argc, byte** argv);
    }
}
